{
  "openapi": "3.1.0",
  "info": {
    "title": "Your API Title",
    "version": "1.0.0",
    "description": "API Documentation"
  },
  "servers": [
    {
      "url": "http://localhost:5000/api",
      "description": "Local server"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {},
  "tags": []
}