# name: 'Push to Redocly'

# on:
#   push:
#     branches:
#       - 'main'

# jobs:
#   push:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       statuses: write
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: 'Push files and wait for deployment'
#         uses: redocly/reunite-push-action@v1
#         with:
#           organization: 'dev-ziq6t'
#           project: 'automation-test'
#           mountPath: '/realtimechatapp/rtc'
#           files: 'openapi.yaml'
#           ignoreLinkChecker: 'true'
#           domain: 'https://app.cloud.redocly.com'
#         env:
#           REDOCLY_AUTHORIZATION: {{ secrets.REDOC_KEY }}




name: 'Push to Redocly'

on:
  push:
    branches:
      - 'main'

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install  # Installs root-level dependencies

      - name: Install dependencies in Backend
        run: npm install
        working-directory: ./Backend

      - name: Generate OpenAPI docs
        run: npm run generate-docs
        working-directory: ./Backend

      - name: Move openapi.yaml to root
        run: mv Backend/openapi.yaml ./openapi.yaml

      - name: 'Push files and wait for deployment'
        uses: redocly/reunite-push-action@v1
        with:
          organization: 'dev-ziq6t'
          project: 'automation-test'
          mountPath: '/realtimechatapp/rtc'
          files: 'openapi.yaml'
          ignoreLinkChecker: 'true'
          domain: 'https://app.cloud.redocly.com'
        env:
          REDOCLY_AUTHORIZATION: ${{ secrets.REDOC_KEY }}
