name: 'Push to Redocly'

on:
  push:
    branches:
      - 'main'

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: 'Push files and wait for deployment'
        uses: redocly/reunite-push-action@v1
        with:
          organization: 'dev-ziq6t'
          project: 'automation-test'
          mountPath: '/realtimechatapp/rtc'
          ignoreLinkChecker: 'true'
          files: 'openapi.yaml'
          domain: 'https://app.cloud.redocly.com'
        env:
          REDOCLY_AUTHORIZATION: ${{ secrets.REDOC_KEY }}


#           mountPath: /realtimechatapp/rtc-2
#           files: Backend/openapi.yaml