# name: Deploy RealTimeChatApp API to Redocly
# description: Automatically deploys API documentation to Redocly when changes are pushed to the main branch.
# on:
#   push:
#     branches:
#       - 'main'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       statuses: write
#     steps:
#       # Step 1: Checkout the repository
#       - name: Checkout Code
#         uses: actions/checkout@v4
#       # Step 2: Set up Node.js
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '16'
#       # Step 3: Install Redocly CLI
#       - name: Install Redocly CLI
#         run: npm install -g @redocly/cli
#       # Step 4: Lint OpenAPI file
#       - name: Lint OpenAPI File
#         run: redocly lint openapi.yaml
#       # Step 5: Debug File Presence
#       - name: Check File
#         run: |
#           ls -la
#           cat openapi.yaml
#       # Step 6: Deploy to Redocly
#       - name: Push files and wait for deployment
#         uses: redocly/reunite-push-action@v1
#         with:
#           organization: 'dev-ziq6t'
#           project: 'automation-test'
#           mountPath: '/realtimechatapp'
#           files: 'openapi.yaml'
#           domain: 'https://app.cloud.redocly.com'
#           githubToken: {{ secrets.GITHUB_TOKEN }}
#         env:
#           REDOCLY_AUTHORIZATION: {{ secrets.REDOC_KEY }}  # Updated to new secret 



name: Push to Redocly
description: Deploys API documentation with manual push and folder support.

on:
  push:
    branches:
      - 'main'

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    timeout-minutes: 10
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # Step 3: Install Redocly CLI
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli
      # Step 4: Deploy specific folder to Redocly
      - name: Push to Redocly
        env:
          REDOCLY_AUTHORIZATION: ${{ secrets.REDOC_KEY }}
        run: |
          # Copy files to a docs folder if needed
          mkdir -p docs
          cp openapi.yaml docs/
          timeout 600 redocly push openapi.yaml dev-ziq6t/automation-test --branch rem/cicd/rem_01k0pepcng95tex0b2pareve1r-main --mount-path /realtimechatapp --upsert
          echo "Push completed with exit code $?"