name: Deploy API Docs to Redocly
description: Automatically deploys API documentation to Redocly when changes are pushed to the main branch.
on:
  push:
    branches:
      - main
jobs:
  deploy-to-redocly:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # Step 3: Install Redocly CLI
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli
      # Step 4: Lint OpenAPI file
      - name: Lint OpenAPI File
        run: redocly lint openapipyaml
      # Step 5: Deploy to Redocly
      - name: Push to Redocly
        env:
          REDOCLY_API_KEY: ${{ secrets.AUTO }}
        run: |
          redocly push openapipyaml dev-ziq6t/automation-test \
          --api-key $REDOCLY_API_KEY \
          --branch main